name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        cache: true # Enable caching for Flutter SDK

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Check formatting
      run: dart format .

  build-windows:
    runs-on: windows-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        cache: true

    - name: Get dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows --release

    - name: Run packaging script
      run: .\package_windows.ps1
      shell: powershell

    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: EdenUpdater_Windows.zip
        retention-days: 7

  build-linux:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        cache: true

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev bc

    - name: Get dependencies
      run: flutter pub get

    - name: Build Linux
      run: flutter build linux --release

    - name: Run packaging script
      run: |
        chmod +x package_linux.sh
        echo "n" | ./package_linux.sh
      shell: bash

    - name: Upload Linux build
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: EdenUpdater_Linux.tar.gz
        retention-days: 7

  build-android:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle' # Cache Gradle dependencies

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        cache: true

    - name: Get dependencies
      run: flutter pub get

    - name: Build Android
      run: flutter build apk --release

    - name: Package Android build
      run: |
        mkdir -p eden_updater_android
        cp build/app/outputs/flutter-apk/app-release.apk eden_updater_android/EdenUpdater.apk

    - name: Upload Android build
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: eden_updater_android/EdenUpdater.apk
        retention-days: 7